#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path.cwd()
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import pyarrow.parquet as pq  # noqa: E402

from ge.run_suite import load_suite_doc, suite_columns, validate  # noqa: E402
from govlib.contracts import load_catalog, load_registry, protected_columns, schema_fields  # noqa: E402
from govlib.fixtures import TOKEN_RE, content_hash, manifest_path  # noqa: E402

errors: list[str] = []
summary: list[str] = ["### ge-gate", "", "| dataset | rows | expectations | failed | verdict |", "|---|---|---|---|---|"]


def err(msg: str) -> None:
    errors.append(msg)
    print(f"::error title=ge-gate::{msg}")


def warn(msg: str) -> None:
    print(f"::warning title=ge-gate::{msg}")


def check_dataset(ds, catalog) -> None:
    n_before = len(errors)
    print(f"\n=== {ds.name}  suite={ds.ge_suite}  fixture={ds.fixture}")
    fields = [f.name for f in schema_fields(ds.schema, root=ROOT)]
    # A. suite hygiene
    try:
        doc = load_suite_doc(ROOT / ds.ge_suite)
    except (OSError, ValueError) as e:
        err(f"{ds.name}: cannot load suite {ds.ge_suite}: {e}")
        return
    missing = sorted(suite_columns(doc) - set(fields))
    if missing:
        err(f"{ds.name}: suite {ds.ge_suite} references column(s) {missing} that are not in the contract "
            f"schema {ds.schema} — was a field renamed or dropped without updating the semantic contract?")
    # B. fixture shape
    fx = ROOT / ds.fixture
    if not fx.exists():
        err(f"{ds.name}: fixture {ds.fixture} missing — run python scripts/make_fixture.py")
        return
    table = pq.read_table(fx)
    cols = table.column_names
    extra = sorted(set(cols) - set(fields))
    if extra:
        err(f"{ds.name}: fixture has column(s) {extra} that the contract does not define")
    stale = [f for f in fields if f not in cols]
    if stale:
        warn(f"{ds.name}: fixture is stale — contract field(s) {stale} are absent; regenerate with scripts/make_fixture.py")
    # C. manifest integrity
    mp = manifest_path(fx)
    if not mp.exists():
        err(f"{ds.name}: manifest {mp.relative_to(ROOT)} missing")
    else:
        m = json.loads(mp.read_text())
        if m.get("rows") != table.num_rows:
            err(f"{ds.name}: manifest says {m.get('rows')} rows, fixture has {table.num_rows}")
        if m.get("content_sha256") != content_hash(fx):
            err(f"{ds.name}: fixture content does not match its manifest hash — regenerate instead of editing Parquet by hand")
        floor = int(m.get("min_per_stratum", 1))
        thin = {k: v["sampled"] for k, v in (m.get("strata") or {}).items() if v.get("sampled", 0) < floor}
        if thin:
            err(f"{ds.name}: strata below the floor of {floor}: {thin}")
        if not m.get("strata"):
            err(f"{ds.name}: manifest records no strata — the fixture's coverage is unproven")
        print(f"manifest: {table.num_rows} rows, {len(m.get('strata', {}))} strata (all >= {floor}), "
              f"injected bad rows: {len(m.get('injected_bad_rows', []))}, key fp {m.get('fixtures_key_fingerprint')}")
    # D. PII leak check
    guarded = set(protected_columns(catalog, ds.table)) | ({catalog.subject_key} if catalog else set())
    for c in sorted(guarded & set(cols)):
        values = [v for v in table.column(c).to_pylist() if v is not None]
        leaks = sum(1 for v in values if not (isinstance(v, str) and TOKEN_RE.match(v)))
        if leaks:
            err(f"{ds.name}: PII LEAK — fixture column '{c}' has {leaks} value(s) that are not HMAC tokens "
                f"(values withheld). Fixtures must be generated by scripts/make_fixture.py")
        else:
            print(f"pii: {c} — {len(values)} values, all tokenized")
    # E. semantic contract
    if missing:
        summary.append(f"| {ds.name} | {table.num_rows} | {len(doc['expectations'])} | n/a | ❌ suite/contract mismatch |")
        return
    df = table.to_pandas()
    results = validate(df, doc)
    failed = [r for r in results if not r.success]
    print(f"{'#':>3}  {'expectation':52s} {'target':26s} result")
    for r in results:
        status = "ok" if r.success else f"FAIL unexpected={r.unexpected_count} sample={r.sample}" + (f" error={r.error}" if r.error else "")
        print(f"{r.index + 1:>3}  {r.expectation_type:52s} {r.target:26s} {status}")
    for r in failed:
        err(f"{ds.name}: {r.expectation_type}({r.target}) failed — {r.unexpected_count} unexpected value(s), e.g. {r.sample}"
            + (f"; error: {r.error}" if r.error else ""))
    ok = len(errors) == n_before
    summary.append(f"| {ds.name} | {table.num_rows} | {len(results)} | {len(failed)} | {'✅ pass' if ok else '❌ fail'} |")


def main() -> int:
    registry = load_registry(root=ROOT)
    catalog = load_catalog(root=ROOT)
    targets = [d for d in registry.values() if d.fixture]
    if not targets:
        err("no dataset in contracts/registry.yml declares a fixture: — nothing proves the semantic contracts")
    for ds in targets:
        check_dataset(ds, catalog)
    report = "\n".join(summary) + "\n"
    print("\n" + report)
    if os.environ.get("GITHUB_STEP_SUMMARY"):
        with open(os.environ["GITHUB_STEP_SUMMARY"], "a", encoding="utf-8") as fh:
            fh.write(report)
    print("ge-gate: PASS" if not errors else f"ge-gate: FAIL — {len(errors)} problem(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
